### ISSUE TITLE
About evaluation 

### ISSUE THREAD

**Issue by urchade** [yyDing1/GNER#3]
Hi,
Congrats for the great work.
I have a question about evaluation for OOD benchmark. Are you including "else" label for the evaluation?

I have recently notice that UniversalNER remove them, but GLiNER does not

Thank you

**Comment by yyDing1** [comment]
Thanks for your attention!

Are you referring to MIT and CrossNER? We don't include the "else" label for the evaluation.

**Comment by urchade** [comment]
Thanks!

Do you know if Gollie do include or not ?

because in GLiNER, I didn't exclude them

**Comment by yyDing1** [comment]
There doesn't seem to be a particular note in Gollie. I'm confused that there doesn't seem to be an "else" tag in the raw data from MIT and CrossNER. Our data source comes from:

- Movie: https://groups.csail.mit.edu/sls/downloads/movie
- Restaurant: https://groups.csail.mit.edu/sls/downloads/restaurant
- CrossNER: https://github.com/zliucr/CrossNER/tree/main/ner_data

Are you processing the data by adding an "else" label?

Please correct me if anything is wrong here.

**Comment by urchade** [comment]
I am also confused. Maybe it is called misc in your case

I have used data preprocessed by: https://github.com/BeyonderXX/InstructUIE

for instance here are the labels for music data which include an else label:

```["location", "event", "country", "band", "person", "song", "musical artist", "music genre", "else", "album", "organization", "award", "musical instrument"]```

**Comment by yyDing1** [comment]
I rechecked their papers and GitHub repositories,

- InstructUIE: They included an "else" tag.
- UniNER: They did not include it, as can be seen from the test data they released [here](https://github.com/universal-ner/universal-ner/tree/main/src/eval/test_data).
- Gollie: They mentioned "misc" in the "error analysis" section, so I guess they included an "else" tag. (Btw, I still notice some pre-processing scripts w/o "else" tag in their repo [here](https://github.com/hitz-zentroa/GoLLIE/blob/main/configs/data_configs/crossner_ai_wo_misc_config.json).

If there is anything I missed, please feel free to remind me.

**Comment by urchade** [comment]
Thank you very much for yours answers. 
It seems that evaluation are not exactly the same for everyone.
