### ISSUE TITLE
Key Questions on Model Training and Evaluation

### ISSUE THREAD

**Issue by G17-Ki** [yyDing1/GNER#4]
After reading your paper, I understand that you used a two-stage training process: the first stage involved training with Pile-NER, and the second stage involved fine-tuning with AnatEM and 17 other datasets. I have the following questions:

1. Are the Zero-shot evaluation results reported in the paper based on the first stage of training or the second stage of training?
2. During the second stage of training, did you combine the 18 datasets into a single large dataset to train one model, or did you fine-tune different models for each of the 18 datasets?

**Comment by yyDing1** [comment]
Thanks for your attention.

**To Question 1**: The zero-shot results are based on the first stage.

**To Question 2**: We randomly select 10,000 data points from each dataset and combine them into a mixed dataset, which is then used for fine-tuning.

**Comment by G17-Ki** [comment]
Thank you very much for your reply. I have another question.

How was the [Task Adaptation] part of the article mentioned using the Pile-NER dataset trained? Is it continue pretrain, SFT, or instruction tuning?

**Comment by yyDing1** [comment]
We perform instruction tuning based on Flan-T5 and Llama. The instruction template can be found [here](https://github.com/yyDing1/GNER/blob/main/assets/task_schema.png).
For further details, please refer to the training scripts and our papers.
