### ISSUE TITLE
About model ckpt 

### ISSUE THREAD

**Issue by wyclike** [yyDing1/GNER#6]
could you please provide the post-supervised checkpoint for the llama-7b and flan-t5-xxl?

**Comment by yyDing1** [comment]
Unfortunately, the checkpoint files for the flan-t5-xxl and llama models were lost during transfer due to their large sizes and unstable transmission. We welcome replication efforts, and we also plan to replicate the models ourselves.

**Comment by wyclike** [comment]
I apologize for my previous doubts. I have replicated your results, and they are indeed solid.
