### ISSUE TITLE
Training Data Preperation

### ISSUE THREAD

**Issue by parzival1l** [yyDing1/GNER#8]
Hello @yyDing1  , 

First of all, this paper was a great read. Thank you for that. I am also working the zero-shot prediction of NERs. Currently I am trying to replicate the same data format to IT llama3.1-8B-Instruct model. I tried making individual calls to gner_dataset.py but have been unsuccessful, if you could provide some instructions on creating the data for training it would be of a huge help.

**Comment by yyDing1** [comment]
Thank you for your interest in our work.

Below is an example of calling `gner_dataset.py`
https://github.com/yyDing1/GNER/blob/16d30d5ab3300741d019f09baa26dca4cb351e16/src/run.py#L218-L225

I hope this is helpful. If you continue to experience issues, could you provide any specific code snippets you’ve tried or any error messages you encountered?

**Comment by parzival1l** [comment]
Thanks for your response, I tried the same in debug mode - from run.py as recommended but I'm getting an error from the load_dataset call. 
My datasets package version is '2.21.0' 
![image](https://github.com/user-attachments/assets/28977fb9-f4c2-41c6-8588-0caa1d340697)

**Comment by yyDing1** [comment]
It seems that higher versions of datasets do not support this. You could try downgrading the `datasets` library to version 2.17 or 2.18, as mentioned in https://github.com/yyDing1/GNER/issues/1.

**Comment by parzival1l** [comment]
Thanks a lot, it worked.
